#!/usr/bin/env bash
# Install and configure HAProxy 1.6 on a new Ubuntu 16.04 server

apt-get -y update
apt-get -y install 'haproxy=1.6.*'

cat >> /etc/haproxy/haproxy.cfg << EOF
backend web-backend
	balance roundrobin
	mode http
	server 18644-web-01 44.192.247.200 check
	server 18644-web-02 18.204.220.15 check
frontend web-frontend
	bind *:80
	mode http
	default_backend web-backend
EOF

service haproxy restart
